# Generated by Django 3.2.11 on 2022-01-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Твое ФИО')),
                ('selfy', models.FileField(null=True, upload_to='videos/', verbose_name='Аватар')),
                ('description', models.TextField(max_length=511, verbose_name='Немного о себе')),
            ],
            options={
                'verbose_name': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип съемки')),
                ('price', models.PositiveIntegerField(default=0, help_text='руб/час', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тип съемки',
                'verbose_name_plural': 'Типы съемки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('lastName', models.CharField(max_length=255, verbose_name='Фамилия заказчика')),
                ('eventDate', models.DateField(auto_now_add=True, verbose_name='Дата съемки')),
                ('timeWork', models.PositiveIntegerField(default=0, help_text='часов', verbose_name='Время съемки')),
                ('suggestions', models.TextField(blank=True, max_length=511, verbose_name='Пожелания заказчика')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона заказчика')),
                ('email', models.EmailField(max_length=127, verbose_name='Email заказчика')),
                ('typesVideos', models.ManyToManyField(to='film_site.VideoType', verbose_name='Типы съемки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='MyWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название видеоролика')),
                ('videoFile', models.FileField(null=True, upload_to='videos/', verbose_name='Видеоролик')),
                ('videoType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_site.videotype', verbose_name='Типы съемки видеоролика')),
            ],
            options={
                'verbose_name': 'Мою работу',
                'verbose_name_plural': 'Мои работы',
            },
        ),
    ]
