# Generated by Django 3.2.11 on 2022-01-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'Обо мне', 'verbose_name_plural': 'Обо мне'},
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='selfy',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Аватар'),
        ),
        migrations.RemoveField(
            model_name='myworks',
            name='videoType',
        ),
        migrations.AddField(
            model_name='myworks',
            name='videoType',
            field=models.ManyToManyField(to='film_site.VideoType', verbose_name='Типы съемки видеоролика'),
        ),
    ]
