# Generated by Django 3.2.11 on 2022-01-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0003_auto_20220119_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='typesVideos',
        ),
        migrations.AddField(
            model_name='order',
            name='typeVideo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='film_site.videotype', verbose_name='Тип съемки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='eventDate',
            field=models.DateField(verbose_name='Дата съемок'),
        ),
    ]
