# Generated by Django 3.2.11 on 2022-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0004_auto_20220120_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='name',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='firstName',
            field=models.CharField(default=1, max_length=255, verbose_name='Твое имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='lastName',
            field=models.CharField(default=1, max_length=255, verbose_name='Твоя фамилия'),
            preserve_default=False,
        ),
    ]
