# Generated by Django 3.2.11 on 2022-01-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0005_auto_20220120_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotype',
            name='slug',
            field=models.SlugField(default='type', max_length=32, verbose_name='Короткое название (на англ.)'),
        ),
    ]
