# Generated by Django 3.2.11 on 2022-02-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0006_videotype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myworks',
            name='videoType',
        ),
        migrations.AddField(
            model_name='myworks',
            name='videoType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='film_site.videotype', verbose_name='Типы съемки видеоролика'),
            preserve_default=False,
        ),
    ]
