# Generated by Django 3.2.11 on 2022-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0007_auto_20220202_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='рублей', max_digits=6, verbose_name='Итоговая цена закза'),
        ),
    ]
