# Generated by Django 3.2.11 on 2022-02-06 14:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0008_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='videoFile',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Видеоролик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='рублей', max_digits=8, verbose_name='Итоговая цена заказа'),
        ),
    ]
