# Generated by Django 3.2.11 on 2022-02-12 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0009_auto_20220206_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eventTime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время начала съемок'),
        ),
    ]
